### ISSUE TITLE
Forgery(:internet).email_address - whitespace in email address

### ISSUE THREAD

**Issue by fionaom** [sevenwire/forgery#53]
This generates invalid emails such as: 

"cpalmer@group buy united.biz"
"pday@deliver the deals.biz"
"jlawson@steal the deal.name"
"arodriguez@wagjag.net"
"aortiz@all buys.gov"
"kflores@smart canucks.com"
"jpeters@yipit.org"
"bking@dream ninja.info"
"fdean@toronto deals online.edu"
"jclark@red flag deals.mil"
"thudson@miser mcgee.info"
"kbrooks@yipit.com"
"jholmes@buy battle.edu"
"sharper@dealbot.org"
"wholmes@toronto deals online.net"
"ksmith@bigmouse.name"
"dgeorge@steal the deal.edu"
"wford@great deal of the day.name"
"breynolds@one spout.net"
"lmoore@bigmouse.gov"
"wkim@dealery.com"
"mburns@angry buys.name"
"emills@wagjag.biz"
"jduncan@angry buys.name"
"polson@yipit.com"
"jarnold@miser mcgee.gov"
"jlewis@sweet ontario deals.biz"
"kryan@yipit.biz"
"dfisher@angry buys.org"
"lsullivan@dealery.info"

**Comment by brandonarbini** [comment]
I don't think is is an issue anymore.
