### ISSUE TITLE
Forgery::Address.phone returns invalid phone numbers

### ISSUE THREAD

**Issue by ludwigschubert** [sevenwire/forgery#54]
While the `#-(###)###-####` format is simple enough, it creates phone numbers which are not E164 compliant.

This is an issue if you want to introduce phone number plausibility checking from [Phony](https://github.com/floere/phony) into your model and suddenly all your tests fail randomly.

Maybe the Phony guys could help with a generator? It seems nontrivial. For now I use a preset country code and just generate the last 7 digits of the phone number randomly.

**Comment by lacostenycoder** [comment]
This feature is still broken.  Using it causes my specs to fail for phones now that I'm using https://github.com/daddyz/phonelib  so will need to probably switch Faker or something unless this can be fixed.
