### ISSUE TITLE
Separate Dictionary sets by language

### ISSUE THREAD

**Issue by rurounijones** [sevenwire/forgery#6]
I am looking at Forgery for creating fake data. The data I am creating will not be in English (And not using a western alphabet).

In the short term I will just override the dictionaries in my app but in future it would be great if we could namespace the dictionaries by language and build up a multi-lingual + alphabet forgery library.

**Comment by felipefontoura** [comment]
Hello I had the same issue, but I was created a new gem as Forgery extension: https://github.com/internetsistemas/brazilian_forgery

But definitely have a multilingual support is a better idea.
