### ISSUE TITLE
Lorem Ipsum always generates the same string

### ISSUE THREAD

**Issue by JD-Kaplan** [sevenwire/forgery#75]
Seems like it should generate random Lorem Ipsum strings? Can't use it for anything that requires unique text.

**Comment by brandonarbini** [comment]
Well, that's kind of the idea behind Lorem Ipsum. However, we did think of this case and it will take a `:random` option as well (https://github.com/sevenwire/forgery/blob/master/lib/forgery/forgery/lorem_ipsum.rb#L101). Did you try that?

**Comment by JD-Kaplan** [comment]
Yes, discovered that just a short while ago. I did find that when I generate 100 lines with 8-16 words as the 'n' value, I only get around 94 unique strings. I guess what I need is beyond the scope of this project, which is fine.
