### ISSUE TITLE
Release a Ruby 2.4 compatible version with fixed fixnum deprecation warnings

### ISSUE THREAD

**Issue by spickermann** [sevenwire/forgery#79]
Hi @kiela 

We already discussed in https://github.com/sevenwire/forgery/pull/77 that there will be a new version released that fixes the deprecation warnings in Ruby 2.4

I opened this issue to make it more visible to others that this issue is already fixed and a new version is coming soon.

Cheers

**Comment by sumitngupta** [comment]
<3

**Comment by Oshuma** [comment]
Any update on when this gem will be pushed?

**Comment by epidemian** [comment]
Hi! We're also getting hit by these deprecation warnings. Is there something i can do to help with the release?

**Comment by brandonarbini** [comment]
Fixed by #84.
