### ISSUE TITLE
Fixnum is deprecated  

### ISSUE THREAD

**Issue by efranco89** [sevenwire/forgery#82]
/home/efranco/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/forgery-0.6.0/lib/forgery/forgery/lorem_ipsum.rb:51: warning: constant ::Fixnum is deprecated

**Comment by franklinyu** [comment]
Duplicate of #79

**Comment by brandonarbini** [comment]
Fixed by #84.
